apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: io-service-hpa-memory
  namespace: magisterka
  labels:
    app: io-service
    hpa-strategy: memory
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: io-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
