apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: magisterka-ingress
  namespace: magisterka
  labels:
    app: magisterka
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - http:
        paths:
          - path: /cpu
            pathType: Prefix
            backend:
              service:
                name: cpu-service
                port:
                  number: 80
          - path: /io
            pathType: Prefix
            backend:
              service:
                name: io-service
                port:
                  number: 80
