apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service
  namespace: magisterka
  labels:
    app: echo-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-service
  template:
    metadata:
      labels:
        app: echo-service
        tier: backend
    spec:
      # --- POPRAWKA 1: Wymuszenie instalacji na apps-pool ---
      nodeSelector:
        workload: apps
      containers:
        - name: echo-service
          # --- POPRAWKA 2: Ścieżka do Artifact Registry w GCP (Zmień TWÓJ_ID_PROJEKTU) ---
          image: europe-west3-docker.pkg.dev/magisterka-497513/magisterka-repo/echo-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10