apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-service-hpa-custom
  namespace: magisterka
  labels:
    app: cpu-service
    hpa-strategy: custom-rps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpu-service
  minReplicas: 1
  maxReplicas: 30
  metrics:
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: "100"
