apiVersion: v1
kind: Service
metadata:
  name: cpu-service
  namespace: magisterka
  labels:
    app: cpu-service
spec:
  type: ClusterIP
  selector:
    app: cpu-service
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
